<?php
/**
 * Razorpay Payment Processing
 */
$pageTitle = 'Payment - Razorpay';
require_once 'includes/header.php';

$orderNumber = $_GET['order'] ?? '';
if (empty($orderNumber)) {
    header("Location: cart.php");
    exit;
}

$db = getDB();
$stmt = $db->prepare("SELECT * FROM orders WHERE order_number = ?");
$stmt->execute([$orderNumber]);
$order = $stmt->fetch();

if (!$order) {
    header("Location: cart.php");
    exit;
}

// Razorpay configuration
// NOTE: Replace with your actual Razorpay credentials
$razorpayKeyId = 'rzp_test_XXXXXXXXXXXXXXX'; // Your Razorpay Key ID
$razorpayKeySecret = 'YOUR_RAZORPAY_SECRET'; // Your Razorpay Key Secret
?>

<section class="page-hero" style="padding: 140px 0 60px;">
  <div class="container">
    <h1>Complete Payment</h1>
    <p>Order #<?php echo e($orderNumber); ?></p>
  </div>
</section>

<section class="section-pad" style="padding-top: 40px;">
  <div class="container">
    <div style="max-width: 600px; margin: 0 auto; background: white; padding: 40px; border-radius: 16px; box-shadow: var(--shadow-md); text-align: center;">
      
      <div style="margin-bottom: 32px;">
        <div style="font-size: 3rem; margin-bottom: 16px;">&#128179;</div>
        <h2 style="font-family: 'Playfair Display', serif; color: var(--bark); margin-bottom: 8px;">Pay with Razorpay</h2>
        <p style="color: var(--text-light);">UPI, Cards, Netbanking & Wallets</p>
      </div>
      
      <div style="background: var(--cream); padding: 24px; border-radius: 12px; margin-bottom: 32px;">
        <div style="font-size: 0.9rem; color: var(--text-light); margin-bottom: 8px;">Amount to Pay</div>
        <div style="font-family: 'Playfair Display', serif; font-size: 2.5rem; font-weight: 900; color: var(--forest);">
          <?php echo formatPrice($order['total_amount']); ?>
        </div>
      </div>
      
      <div style="background: #fff3cd; border: 1px solid #ffc107; padding: 16px; border-radius: 8px; margin-bottom: 24px; text-align: left; font-size: 0.9rem;">
        <strong>&#9888; Demo Mode:</strong> This is a demo integration. To enable real payments:
        <ol style="margin-top: 8px; padding-left: 20px; line-height: 1.8;">
          <li>Sign up at <a href="https://razorpay.com" target="_blank" style="color: var(--terracotta);">razorpay.com</a></li>
          <li>Get your API keys from Dashboard > Settings > API Keys</li>
          <li>Update <code>config/payment.php</code> with your credentials</li>
          <li>Include Razorpay checkout script in this page</li>
        </ol>
      </div>
      
      <!-- Razorpay Integration Code (Demo) -->
      <button id="rzp-button" class="btn-primary" style="width: 100%; padding: 16px; font-size: 1.1rem;">
        Pay <?php echo formatPrice($order['total_amount']); ?> with Razorpay
      </button>
      
      <div style="margin-top: 24px;">
        <a href="order_success.php?order=<?php echo e($orderNumber); ?>&demo=1" style="color: var(--terracotta); font-size: 0.9rem;">
          Skip to Order Confirmation (Demo) &#8594;
        </a>
      </div>
      
    </div>
  </div>
</section>

<!-- Razorpay Checkout Script (Demo) -->
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "<?php echo $razorpayKeyId; ?>",
    "amount": <?php echo $order['total_amount'] * 100; ?>, // Amount in paise
    "currency": "INR",
    "name": "Tribal Crafts",
    "description": "Order #<?php echo e($orderNumber); ?>",
    "order_id": "", // This will be generated by Razorpay API
    "handler": function (response){
        // Payment successful
        window.location.href = "order_success.php?order=<?php echo e($orderNumber); ?>&tx=" + response.razorpay_payment_id;
    },
    "prefill": {
        "name": "<?php echo e($order['customer_name']); ?>",
        "email": "<?php echo e($order['customer_email']); ?>",
        "contact": "<?php echo e($order['customer_phone']); ?>"
    },
    "theme": {
        "color": "#C4623A"
    }
};

var rzp = new Razorpay(options);
document.getElementById('rzp-button').onclick = function(e){
    rzp.open();
    e.preventDefault();
}
</script>

<?php require_once 'includes/footer.php'; ?>
